SuppressedFindings:
  - CheckID: kms_cmk_not_deleted_unintentionally
    ResourceID: arn:aws:kms:ap-northeast-2:833453046706:key/35d2458f-3962-4891-854a-eac25c5211c0
    Reason: "Intentional CMK deletion"

  - CheckID: kms_cmk_not_deleted_unintentionally
    ResourceID: arn:aws:kms:ap-northeast-2:833453046706:key/4bbfad5d-f0ec-4206-bd8e-5d74062c70cc
    Reason: "Intentional CMK deletion"

  - CheckID: kms_cmk_not_deleted_unintentionally
    ResourceID: arn:aws:kms:ap-northeast-2:833453046706:key/673945cd-b5a2-4c77-9308-046424099584
    Reason: "Intentional CMK deletion"

  - CheckID: kms_cmk_not_deleted_unintentionally
    ResourceID: arn:aws:kms:ap-northeast-2:833453046706:key/9c48142f-dcbe-42c6-91a9-0cf499447336
    Reason: "Intentional CMK deletion"

  - CheckID: kms_cmk_not_deleted_unintentionally
    ResourceID: arn:aws:kms:ap-northeast-2:833453046706:key/c7331c45-33e8-43d3-b80b-c6d7ab0ce53e
    Reason: "Intentional CMK deletion"

  - CheckID: kms_cmk_not_deleted_unintentionally
    ResourceID: arn:aws:kms:ap-northeast-2:833453046706:key/d2e83dbb-f9ed-4068-a80a-fb726304e31f
    Reason: "Intentional CMK deletion"
